### ISSUE TITLE
MTSDD model phonon drag term dominates slip kinetics

### ISSUE THREAD

**Issue by rcarson3** [llnl/ExaCMech#21]
I've been working on trying to parameterize a nickel material using the MTSDD model, and I'm finding that if I try to drive phonon slip kinetics drag term to zero by setting the `_gam_ro` parameter to some really small value (1e-6 1/s) that this causes the latter `gdot = 1/(1/gdot_r + 1/gdot_w)` to essentially ignore the thermal contribution. However, if I raise this closer to 1e-1 then it starts behaving better.

It seems that it might  be a good idea to check the difference in the magnitude of the gdot_r and gdot_w and if it's over a certain amount we should look at just zeroing out the contribution of the smallest one.

I get that the above is essentially a harmonic mean, so it's behaving like it should. However, it would be nice if we could just turn off the phonon drag term if we're dealing with quasi-static rates. The only reason I bring this up is I've been having trouble finding a set of parameters that allows my system to converge right around the elastic-plastic transition, and from what I can tell it appears related to the phonon slip kinetics term. So, I've been trying to look into ways to turn it off without editing the code to just remove it completely...

@nrbarton thoughts?

**Comment by nrbarton** [comment]
Given the way the kinetics works, you want that drag term to be really large for it cease to be a significant contribution. And that is the cartoon in many quasi-static applications -- the dislocations run so quickly from one set of obstacles to another (gdot_r is large) that the overall dislocation velocity is dominated by the time spent waiting to overcome obstacles by thermal fluctuation.

**Comment by rcarson3** [comment]
I think this might be an area where we could improve the documentation then as my first thoughts aren't to make the contribution I want to turn off much much larger than the other one to turn it off probably because I don't typically make use of the harmonic mean in day to day work but rather the arithmetic mean where it's of course the opposite...
